//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.ServiceEmpleado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SL_WCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Empleado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ML.Empresa))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Ex {
            get {
                return this.ExField;
            }
            set {
                if ((object.ReferenceEquals(this.ExField, value) != true)) {
                    this.ExField = value;
                    this.RaisePropertyChanged("Ex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEmpleado.IEmpleado")]
    public interface IEmpleado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/Add", ReplyAction="http://tempuri.org/IEmpleado/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServiceEmpleado.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Empresa))]
        PL_MVC.ServiceEmpleado.Result Add(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/Add", ReplyAction="http://tempuri.org/IEmpleado/AddResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceEmpleado.Result> AddAsync(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/Update", ReplyAction="http://tempuri.org/IEmpleado/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServiceEmpleado.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Empresa))]
        PL_MVC.ServiceEmpleado.Result Update(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/Update", ReplyAction="http://tempuri.org/IEmpleado/UpdateResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceEmpleado.Result> UpdateAsync(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/Delete", ReplyAction="http://tempuri.org/IEmpleado/DeleteResponse")]
        PL_MVC.ServiceEmpleado.Result Delete(int IdEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/Delete", ReplyAction="http://tempuri.org/IEmpleado/DeleteResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceEmpleado.Result> DeleteAsync(int IdEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/GetAll", ReplyAction="http://tempuri.org/IEmpleado/GetAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PL_MVC.ServiceEmpleado.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Empresa))]
        PL_MVC.ServiceEmpleado.Result GetAll(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/GetAll", ReplyAction="http://tempuri.org/IEmpleado/GetAllResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceEmpleado.Result> GetAllAsync(ML.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/GetById", ReplyAction="http://tempuri.org/IEmpleado/GetByIdResponse")]
        PL_MVC.ServiceEmpleado.Result GetById(int IdEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleado/GetById", ReplyAction="http://tempuri.org/IEmpleado/GetByIdResponse")]
        System.Threading.Tasks.Task<PL_MVC.ServiceEmpleado.Result> GetByIdAsync(int IdEmpleado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpleadoChannel : PL_MVC.ServiceEmpleado.IEmpleado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadoClient : System.ServiceModel.ClientBase<PL_MVC.ServiceEmpleado.IEmpleado>, PL_MVC.ServiceEmpleado.IEmpleado {
        
        public EmpleadoClient() {
        }
        
        public EmpleadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL_MVC.ServiceEmpleado.Result Add(ML.Empleado empleado) {
            return base.Channel.Add(empleado);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceEmpleado.Result> AddAsync(ML.Empleado empleado) {
            return base.Channel.AddAsync(empleado);
        }
        
        public PL_MVC.ServiceEmpleado.Result Update(ML.Empleado empleado) {
            return base.Channel.Update(empleado);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceEmpleado.Result> UpdateAsync(ML.Empleado empleado) {
            return base.Channel.UpdateAsync(empleado);
        }
        
        public PL_MVC.ServiceEmpleado.Result Delete(int IdEmpleado) {
            return base.Channel.Delete(IdEmpleado);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceEmpleado.Result> DeleteAsync(int IdEmpleado) {
            return base.Channel.DeleteAsync(IdEmpleado);
        }
        
        public PL_MVC.ServiceEmpleado.Result GetAll(ML.Empleado empleado) {
            return base.Channel.GetAll(empleado);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceEmpleado.Result> GetAllAsync(ML.Empleado empleado) {
            return base.Channel.GetAllAsync(empleado);
        }
        
        public PL_MVC.ServiceEmpleado.Result GetById(int IdEmpleado) {
            return base.Channel.GetById(IdEmpleado);
        }
        
        public System.Threading.Tasks.Task<PL_MVC.ServiceEmpleado.Result> GetByIdAsync(int IdEmpleado) {
            return base.Channel.GetByIdAsync(IdEmpleado);
        }
    }
}
